"use client";
import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillInstagram,
  AiFillMail,
  AiOutlineMenu,
  AiOutlineClose,
} from "react-icons/ai";
import krutk from "/public/krutk1.jpg";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import Typewriter from "typewriter-effect";

export default function Home() {
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);

  const toggleDropdown = () => {
    setIsDropdownOpen(!isDropdownOpen);
  };

  return (
    <div>
      <Head>
        <title>Kumar Utkarsh - Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-[#2f2e31] md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="pt-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl" />
            <ul className="flex items-center">
              <li>
                <div className="relative">
                  <button
                    className="bg-transparent text-gray-800 dark:text-white px-4 py-2 border-none rounded-md ml-8 focus:outline-none"
                    onClick={toggleDropdown}
                  >
                    {isDropdownOpen ? (
                      <AiOutlineClose className="text-2xl" />
                    ) : (
                      <AiOutlineMenu className="text-2xl" />
                    )}
                  </button>
                  {isDropdownOpen && (
                    <div className="absolute right-0 -mt-10 mr-14 bg-transparent text-gray-800 dark:text-white rounded-md flex space-x-2">
                      <Link
                        className="block px-3 py-2 hover:bg-gray-200 dark:hover:bg-gray-600"
                        href="/contacts"
                      >
                        Contacts
                      </Link>
                      {/* <Link
                        className="block px-3 py-2 hover:bg-gray-200 dark:hover:bg-gray-600"
                        href="/portfolio"
                      >
                        Portfolio
                      </Link> */}
                      <a
                        className="block px-3 py-2 hover:bg-gray-200 dark:hover:bg-gray-600"
                        href="/resume.pdf"
                        download
                      >
                        Resume
                      </a>
                    </div>
                  )}
                </div>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              KUMAR UTKARSH
            </h2>
            <h4 className="text-2xl py-2 dark:text-white md:text-3xl">
              <Typewriter
                options={{
                  strings: ['Full Stack Developer', 'Based in India'],
                  autoStart: true,
                  loop: true,
                }}
              />
            </h4>

            <p className="text-sm py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I am a Full Stack Developer with expertise in Frameworks /
              Programming Languages{" "}
              <span className="underline">ReactJS</span> +{" "}
              <span className="underline">NextJS</span> +{" "}
              <span className="underline">NodeJS</span> +{" "}
              <span className="underline">GraphQL</span> etc.
            </p>
            <div className="text-2xl flex justify-center gap-12 py-3 text-gray-600 dark:text-gray-400">
              <Link target="_blank" href="https://linkedin.com/in/krutk">
                <AiFillLinkedin />
              </Link>
              <Link
                target="_blank"
                href="https://instagram.com/kumxrutkxrsh"
              >
                <AiFillInstagram />
              </Link>
              <Link target="_blank" href="mailto:utkarshroy28@gmail.com">
                <AiFillMail />
              </Link>
            </div>
            <div className="flex justify-center">
              <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
                <Image src={krutk} layout="fill" objectFit="cover" />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
